### ISSUE TITLE
Xplore Theme Resetting on Reload of Page.

### ISSUE THREAD

**Issue by HarryPearson** [jneale/Xplore#37]
The Codemirror theme seems to persist through refreshing the page however it seems that the xplore-s-"theme" name isn't getting applied to the .page class on initialization of the page.

Line 1076 of snd_xplore_ui UI Script.

`  var current_theme = $('#setting_theme').val();

  //initialize the theme - proposed fix.
  $('.page').addClass('xplore-s-' + current_theme);

  function updateTheme(theme, preview) {
    theme = theme || $('#setting_theme').val();
    $('.page').removeClass('xplore-s-' + current_theme).addClass('xplore-s-' + theme);
    snd_xplore_editor.setOption('theme', theme);
    current_theme = theme;
  }`

**Comment by jneale** [comment]
Good catch! I changed this a couple of days ago and forgot to check the theme when reloading from saved settings.

**Comment by jneale** [comment]
I've fixed this now and updated on Share. It wasn't actually this code, but snd_xplore_main UI macro line 134 which applies the theme setting on page generation. Thanks anyway!
