### ISSUE TITLE
g_user not available when running client script

### ISSUE THREAD

**Issue by mikebski** [jneale/Xplore#38]
g_user is undefined - see attached image

![image](https://user-images.githubusercontent.com/4280588/109028021-6281b280-768f-11eb-83da-71d530715347.png)

**Comment by jneale** [comment]
Hi, g_user is only available in the ServiceNow client and is only accessible if you open Xplore from the button in the ServiceNow header and use the Opener target.
![image](https://user-images.githubusercontent.com/1355440/109128747-af28c480-7747-11eb-9bc6-89a3a2b2a570.png)
