### ISSUE TITLE
Add option to not automatically run when pressing Ctrl+S

### ISSUE THREAD

**Issue by EricMedina024** [jneale/Xplore#39]
I would appreciate if an option to not automatically run the current script when CTRL+S is pressed was added. I have muscle memory to hit CTRL+S constantly to ensure I don't lose work when using any other editors. This muscle memory carries over to the Xplore code editor and I am worried that it may one day lead to me running code that is not finished and causing issues.

**Comment by jneale** [comment]
Noted. Should be able to do this for the next release.

**Comment by EricMedina024** [comment]
@jneale do you think it would be a good idea to disable the auto-run behavior by default? or perhaps take a jetbrains approach and ask what the user's preference is when the shortcut is first used

**Comment by jneale** [comment]
Option added in 4.9.

I'm going to leave it enabled by default for now as that is what people are used to.
