### ISSUE TITLE
Colour choice for .kwd has a very low contrast ratio on dark themes

### ISSUE THREAD

**Issue by n21lv** [jneale/Xplore#44]
It's almost impossible to see keywords like `true` or `false` in the Output tab. In code inspector the colour choice shows a contrast ratio of 1.4. WCAG Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text. Please make it at least WCAG Level AA-compliant.

Further reading: https://webaim.org/resources/contrastchecker/#:~:text=WCAG%20Level%20AAA%20requires%20a,(typically%2024px)%20or%20larger.

**Comment by jneale** [comment]
Hi, please can you share which theme is giving you issues? A screenshot would also be helpful.

Themes are currently in beta and as such will have some issues as they are intended only for CodeMirror and so porting to the wider page is quite a bit of effort.

**Comment by n21lv** [comment]
Hello! I actually experience it in every dark theme. Here I have 3024-night enabled
![image](https://user-images.githubusercontent.com/30559591/118179753-5e6b6280-b43e-11eb-91f2-c8f712464419.png)

I think if you change it to something like `#01a0e4`, it will be much easier on the eye.

**Comment by jneale** [comment]
Fixed in 4.9.
