### ISSUE TITLE
Xplore header obscures script pane for narrower window sizes

### ISSUE THREAD

**Issue by chaorace** [jneale/Xplore#45]
At narrower window sizes, the header bar doesn't seem to reflow correctly:
![1620930530](https://user-images.githubusercontent.com/6462592/118170048-a74bf880-b3f7-11eb-8bc4-bd58a1a5ca00.png)

As you can see in the screenshot, the first 3 or so lines of the code editor are obstructed. This seemed to happen whenever the window's width dimension went below 1000px (at standard page zoom level).

I first noticed this issue using (chromium-based) Qutebrowser, but I can reproduce the issue in firefox under the same conditions.
See below for my full browser info:
```
qutebrowser v1.14.1
Git commit: 21b20116f on master (2021-01-19 19:14:55 +0100)
Backend: QtWebEngine (Chromium 87.0.4280.144)
Qt: 5.15.2
```

**Comment by chaorace** [comment]
My bad, just noticed there's already a PR (#42) for this issue!

**Comment by jneale** [comment]
Thanks, yep! It's on the fix list :)
