### ISSUE TITLE
A GlideElement of type GlideElementVariables will not display in output pane (for non-SCTask/RITM records)

### ISSUE THREAD

**Issue by chaorace** [jneale/Xplore#46]
If you attempt to view the output for a variable field belonging to a record that is not on the `sc_task`/`sc_req_item` table, Xplore will fail to display the result in the output pane and instead appears to load forever:
![1620931628](https://user-images.githubusercontent.com/6462592/118172048-ec712a00-b3f9-11eb-8512-dddffe07b3b3.png)

In the above pictured case, the variables were associated to the record by way of Record Producer.

Worth noting: despite the preview not working for the field itself, it is still possible to view individual variables in the output by dotwalking to them:

![1620931761](https://user-images.githubusercontent.com/6462592/118172373-4a057680-b3fa-11eb-8beb-f0a787a717db.png)

**Comment by jneale** [comment]
Interesting. Please can you try using Xplore 4.8 and see if you get the same thing?

P.S. Would you be happy to share your theme?

**Comment by chaorace** [comment]
Will do that soon-ish when I get a moment alone with the instance.

By the way, I'm actually using Chromium's dark mode switches (via configuration options exposed in Qutebrowser), not a dedicated theme. All the colors you see here are just HSL rotations of the default theme

In any case, here's the color codes, just in case they may offer any inspriation:

Element | Color
------------ | -------------
BG | `#121212`
Accent BG | `#212121`
Light BG | `#28282A`
Error BG | `#3B2C2D`
Warn BG | `#232111`
Info BG | `#1D2E35`
Green BG | `#202D1C`
FG | `#DFDFDF`
Accent FG | `#CCCCCC`
Dark FG | `#B5B5B5`
Gutter FG | `#999999`
Error FG | `#EF827B`
Warn FG | `#B0905C`
Info FG | `#AFB3B5`
Green FG | `#689D64`
Comment FG | `#DF8231`
Keyword FG | `#FFA1FF`
Parameter FG | `#DCA1FF`
Variable FG | `#8CB6FF`
Number Literal FG | `#73C199`
String Literal FG | `#FF8263`
Other Literal FG | `#FDCBFF`
Green Button | `#5CB85C`
Red Button | `#D9534F`
Link | `#5999D8`

**Comment by chaorace** [comment]
I finally got around to testing this. The issue seems to be fixed! I upgraded directly to 4.9, so I'm not sure if the issue was fixed in the prior release or current release.
