### ISSUE TITLE
Object.create

### ISSUE THREAD

**Issue by davidverano** [jneale/Xplore#49]
When using Object.create (see picture) to create new objects with prototypal inheritance xPlore will only show the properties that I have overridden and not the default values from prototype and no methods as I try to show the result.
![image](https://user-images.githubusercontent.com/86000784/122219058-5a07ee80-ceaf-11eb-80fe-6ab0fd9015d6.png)

**Comment by davidverano** [comment]
Just wanted to clarify that the function (greet()) and the lastname property is still there, only xPlore just does not show them in the list of objects that is included in the object john:
![image](https://user-images.githubusercontent.com/86000784/122219703-fd590380-ceaf-11eb-9900-dfec3d013fef.png)

**Comment by jneale** [comment]
Hi,

Please upgrade to the latest version - this bug was fixed in 4.9.
![image](https://user-images.githubusercontent.com/1355440/122221209-faa6e000-cea8-11eb-9afb-f0594d0f8d7d.png)

Thanks!
