### ISSUE TITLE
Javascript error on client opening record

### ISSUE THREAD

**Issue by billwhitney** [jneale/Xplore#50]
Hello.... I am using Xplore successfully on multiple systems, however I have just installed Xplore on a Paris system and I am having the following problem: When I try to "Open Record in Xplore" nothing happens, and I get the following javascript error in the client:

Uncaught TypeError: Cannot read property 'open' of undefined
    at openInXplore (sn_wsd_core_space.do?sys_id=47db04fcdb8bd850b4afe5bcd39619d9&sysparm_record_target=cmn_location&sysparm_record_row=52&sysparm_record_rows=2994&sysparm_record_list=ORDERBYname:862)
    at eval (eval at execute (VM4341 js_includes_doctype.jsx:10840), <anonymous>:1:1)
    at execute (VM4341 js_includes_doctype.jsx:10840)
openInXplore @ sn_wsd_core_space.do?sys_id=47db04fcdb8bd850b4afe5bcd39619d9&sysparm_record_target=cmn_location&sysparm_record_row=52&sysparm_record_rows=2994&sysparm_record_list=ORDERBYname:862
eval @ VM4737:1
execute @ js_includes_doctype.jsx?v=05-04-2021_2116&lp=Wed_Jun_16_09_18_48_PDT_2021&c=14_332:10840

I am able to open Xplore from the Filter Navigator, however the "eye-glasses" banner link does not appear when I refresh the page.

Any ideas?

**Comment by jneale** [comment]
Hi,

The openInXplore function is defined and used exclusively in the Open in Xplore UI Action.

This sounds like the instance or page page you're looking at has a JavaScript error that is preventing client side UI Actions from being processed. Other than that, unfortunately there isn't much I can help with.

Best,
James

**Comment by jneale** [comment]
As above - this issue is likely with the instance being worked on. Not seen anywhere else. Closing.
