### ISSUE TITLE
New feature request - allow definition and retention pane widths

### ISSUE THREAD

**Issue by ch80us** [jneale/Xplore#51]
the default layout is about 40/60 script/information, while manual resizing is nice it does create some temporary cursor issues. It would be a great feature if via a property on the gear the split could be set and retained. I often find myself shrinking the output pane since a full collapse isn't possible.

**Comment by jneale** [comment]
Thanks for the feedback.
I think the cursor issues are only if you have a frame open in the information pane (i.e. logs). And I'm not sure there is much I can do about that.
I'll definitely look at adding the split proportion as a preference and also being able to toggle the info pane.

**Comment by jneale** [comment]
Default editor width setting added in 4.10.
