### ISSUE TITLE
Issue with displaying array containing items with backslashes

### ISSUE THREAD

**Issue by StonegateGuy** [jneale/Xplore#59]
When showing the output of an array (for example when querying a list) that contains a backslash the output is adding extra backslashes to the "gray box" output.  It shows correctly in the text output below the gray box. (assuming this has something to do with its being the JavaScript escape char). For example a field containing a file path such as  "\\Server\Folder1\Folder2\Folder3" is shown as  "\\\\Server\\Folder1\\Folder2\\Folder3" in the gray box at the top. 

![image](https://user-images.githubusercontent.com/16310575/160866224-ba483aac-9ff8-41fb-9eb4-e1fa43c74419.png)

**Comment by jneale** [comment]
Thanks for your comment. This is actually expected behaviour. The grey text box at the top is the JSON version of the object you are viewing so you can easily copy/paste it into another script somewhere if you need it. Cheers!
