### ISSUE TITLE
Resources on stackpath.bootstrapcdn.com being blocked

### ISSUE THREAD

**Issue by erwinel** [jneale/Xplore#60]
Many government networks, including my own workplace, are blocking resources on [stackpath.bootstrapcdn.com](http://stackpath.bootstrapcdn.com/). This causes the `snd_xplore_main.html` page to fail. For security reasons, our cyber team will not divulge why the IP addresses are being blocked, but the best I reason could find on my own was at https://www.ip-tracker.org/blacklist-check.php?ip=Stackpath.bootstrapcdn.com.

I have already forked this repository and [created a fix](https://github.com/erwinel/Xplore) with the following changes:

- [dist/Xplore Developer Toolkit - 4.11 to 4.11.1.xml](https://github.com/erwinel/Xplore/blob/c27de68a6be92c2190230d4cab6589b3b65cf658/dist/Xplore%20Developer%20Toolkit%20-%204.11%20to%204.11.1.xml) - Added update set that applies changes made to version 4.11.
- [dist/Xplore Developer Toolkit - 4.11.1.xml](https://github.com/erwinel/Xplore/blob/c27de68a6be92c2190230d4cab6589b3b65cf658/dist/Xplore%20Developer%20Toolkit%20-%204.11.1.xml) - Added update set to import version 4.11.1.
- [src/UI Macros/snd_xplore_main.html](https://github.com/erwinel/Xplore/blob/c27de68a6be92c2190230d4cab6589b3b65cf658/src/UI%20Macros/snd_xplore_main.html) - Modified to change CDN provider to the same one that [docs.servicenow.com](https://docs.servicenow.com) uses.

Following are the modifications that were made to `snd_xplore_main.html`:

- Original: https://github.com/jneale/Xplore/blob/76efc88716c57eb08f84651bb3a0b6b0e0beb0f5/src/UI%20Macros/snd_xplore_main.html#L106
  Replacement:
  ````html
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous" />
  ````
 
- Original: https://github.com/jneale/Xplore/blob/76efc88716c57eb08f84651bb3a0b6b0e0beb0f5/src/UI%20Macros/snd_xplore_main.html#L881
  Replacement:
  ```html
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script>
  ```

If you'd like me to just submit a pull request, let me know.

**Comment by jneale** [comment]
Thanks for the heads up. I wasn't aware of this, but I've added your fix to the next release.
