### ISSUE TITLE
glide.installation.production is not intended to be used to check if the instance is production

### ISSUE THREAD

**Issue by kr4uzi** [jneale/Xplore#62]
**Reference:** https://support.servicenow.com/kb?id=kb_article_view&sysparm_article=KB0818410
**Quote:** "glide.installation.production" should NOT to be used as a means to differentiate between Production and subproduction instances.

'glide.installation.production' isn't even in the clone preservers so it should not be used because it will be "true" even on subprod (e.g. dev) instances...
Unfortunately i cannot really offer you a replacement for this... if anyone knows a good replacement, please let us know.

**Comment by jneale** [comment]
Thanks for the note. You're absolutely right and this feature is all but deprecated. At the time of building the production check feature in Xplore, that knowledge was not widely available.

If you do want to use it but don't want to rely on the glide flag, then you just need to replace the reference in the processor to glide.installation.production with your own property.

**Comment by jneale** [comment]
No further action will be taken on this. It's not a big deal for users who are using the production flag to disable it after cloning.
