### ISSUE TITLE
Link to Xplore in Now Experience header (San Diego)

### ISSUE THREAD

**Issue by ryandean99** [jneale/Xplore#65]
Since upgrading to San Diego we're not able to see the eyeglass icon in the header to quickly link to Xplore.

One work-arounds is accessing Xplore from the Application menu and pinning it as a favorite. Another work-around is to add a custom slash-common in the SNUtils chrome extension.

If you want to add it as a direct link in the header, there is some code I recently developed to add a service portal link to the user menu. I suppose it could be adapted to add a link to Xplore anywhere in the header. It was originally posted on [this community post](https://community.servicenow.com/community?id=community_question&sys_id=e79c20211bf45910587a11751a4bcb79).

If I get a little time I may try adapting myself and report back here what I find.

**Comment by jneale** [comment]
I wasn't going to bother trying to inject it in Polaris but enough people have requested it that I've decided to go ahead and do it. Thanks for the feedback. Hopefully ServiceNow don't change the DOM too much in future versions!
