### ISSUE TITLE
Scripts do not run after upgrading to Tokyo

### ISSUE THREAD

**Issue by johndahl-now** [jneale/Xplore#66]
After upgrading my San Diego release to Tokyo, Xplore stopped running scripts. The UI loads up fine, but whenever I try to run even the most basic expressions (i.e. **gs.info( 10 );** ), I get the error below:

"InternalError: Can't find method com.glide.script.system.GlideSystemUtilScript.getScriptError(string). (<refname>; line 497)"

The system logs for the transaction do not show anything and a broader system log review doesn't show anything obvious. There are a few errors related to key generation for the com.glide.ui.ServletErrorListener source, but I'm not sure if they are related. They contain key data so I'm hesitant to include them here.

**Comment by johndahl-now** [comment]
Kieran Anson seems to have found the issue. It seems the snd_xplore file line 497 is looking for **._getScriptError(string)** instead of **.getScriptError(string)**. It's strange that the error did not include the leading underscore, but removing it from the line seems to have resolved the issue.

On a side note, there is also a global file (global.JSValidator) that still refers to the function with the leading underscore. I suspect that should be updated as well. I suspect this is an OOB file?

**Comment by jneale** [comment]
Hi John, thanks. That error is actually a misnomer in the error for whatever reason and the function is still _getScriptError() as you have seen in the validator. The problem is that ServiceNow have changed the method so it now requires two arguments - with the second argument being scope. Unfortunately it's not a fix I can just give you in a one liner, but I'll get an update out soon.

**Comment by johndahl-now** [comment]
That makes sense... I was wondering why the code would have the leading underscore and the error would suggest it cannot be found... or that removing the leading underscore would "fix" it... sounds like it just broke it in a different way... it allows the code to run, but maybe ignores any errors?

**Comment by sushant0625** [comment]
Looks like 'scope' argument is required in Tokyo to check if the script in that particular scope supports ESLatest features offered in Tokyo Update. If the application scope is configured to use the latest ES6+ features, the platform will need to transpile it first.

**Comment by jneale** [comment]
Fixed the issue and made sure it's backwards compatible.
