### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by mgrak** [jneale/Xplore#68]
Your app is great, you are super responsive, and my entire team uses it. I would love to be able to donate some cash as a thank you for a great product ServiceNow should license off you and put it in as an OOB feature.

Any way I can send you some cash/free food/alcohol?

**Comment by jneale** [comment]
Thanks for the kind feedback and offer!

You don't need to send me anything, but if you really want to then you can post to the address found at https://sharelogic.com/contact (address to James Neale)
