### ISSUE TITLE
Conflicts with SN Utils when Next Experience is enabled

### ISSUE THREAD

**Issue by iar42** [jneale/Xplore#69]
There seems to be a small conflict in Xplore 4.12 with the SN Utils browser extension:

After updating to 4.12, the SN Utils provided Application and Update set pickers open Xplore instead of the relevant picker list.

To reproduce:
- In SN Utils settings, enable setting "Show (Next UI) or Enhance (UI16) Application and Updateset picker at page load."
- Observe that now clicking on either the Application or Update set pickers that SN Utils provides, the Xplore tab is opened instead of the relevant picker list.

Tested on: Chrome 104.0.5112.102 (Windows 10), SN Utils 6.1.2.9, Tokyo with Next Experience enabled

**Comment by arnoudkooi** [comment]
Thanks for pinging me on Slack Ingimar.
I'll add a fix in SN Utils for this.

**Comment by jneale** [comment]
Thanks guys!
