### ISSUE TITLE
When examining a deep JSON structure it would be useful to allow a "re-run" and stay on the item 

### ISSUE THREAD

**Issue by dhubbard-ag** [jneale/Xplore#70]
When a script outputs a JSON structure, Xplore presents top level attributes in Name/Type/Value list - allowing items to be selected.

It is possible to navigate to a deep item to view.

If "Run" is selected the navigation starts again at the top.

It would be useful to be able "Re-run" the script and "stay" on the item you were previously viewing and get a refreshed update - rather than having to renavigate.

This is (possibly) linked #61

**Comment by jneale** [comment]
It's a good point and something I occasionally come across myself.

**Comment by jneale** [comment]
Navigation has been improved with the updates for #61
