### ISSUE TITLE
Issues in Tokyo

### ISSUE THREAD

**Issue by RahmanM** [jneale/Xplore#76]
Hi there,

Couple of issues. I am using v4.12.

1) In Tokyo by enabling the Next Experience UI the Xplore icon is not showing anymore. 
2) Running the ES6 code returning error in Xplore while it works in Background Script in the same scope e.g. this sample code fails with error "syntax error (<refname>; line 2): JavaScript parse error at line (2) column (40) problem = syntax error (<refname>; line 2)"

```
// ES6
const objectDestructorEs6 = (person) => {
    let n = { name } = person || {}; 
    gs.debug(n)
};

objectDestructorEs6({name: "rahman"});
objectDestructorEs6(null);
```

regards,

**Comment by jneale** [comment]
Thanks.
Support for the Xplore icon in Next Experience was added in version 4.12.1, although it only supports it from Tokyo.
I'll have to look into why ES6 is not being supported and see if it can be added.

**Comment by jneale** [comment]
Changed this to an enhancement request since ServiceNow appear to have introduced a different way of executing ES6 scripts than what Xplore uses.

**Comment by jneale** [comment]
Support for latest ES added in 4.14.

**Comment by RahmanM** [comment]
Thanks James! This is great news. Where can I download the 4.14 version
please? Share is still showing 4.14.

Regards,


Rahman
