### ISSUE TITLE
gs.print, gs.log, gs.info is cutting string

### ISSUE THREAD

**Issue by ajarzyna** [jneale/Xplore#78]
Hi I noticed some strange behaviour for gs.print, gs.log, gs.info in xplore 4.13.
gs.print, gs.log, gs.info does not display strings properly when it includes < >. It simply cuts off all text within <>.

Example:
var testString = '=?iso-8859-2?Q?Kwa=B6niak_<Janusz>_=28PR_Lublin=29?=<jak.kowalski@testdomain.com.pl>';
gs.print('gs.print(TEST string):  ' + testString);
gs.info('gs.info(TEST string): ' + testString);
gs.log('gs.log(TEST string): ' + testString);

Results: 
2023-05-30 11:21:31 (959) global.snd_Xplore.gsprint(TEST string): =?iso-8859-2?Q?Kwa=B6niak__=28PR_Lublin=29?=
2023-05-30 11:21:31 (959) global.snd_Xplore.gsinfo(TEST string): =?iso-8859-2?Q?Kwa=B6niak__=28PR_Lublin=29?=
2023-05-30 11:21:31 (959) global.snd_Xplore.gslog(TEST string): =?iso-8859-2?Q?Kwa=B6niak__=28PR_Lublin=29?=

When I ran the same example in background script all works as expected

*** Script: gs.print(TEST string):  =?iso-8859-2?Q?Kwa=B6niak_<Janusz>_=28PR_Lublin=29?=<jak.kowalski@testdomain.com.pl>
*** Script: gs.info(TEST string): =?iso-8859-2?Q?Kwa=B6niak_<Janusz>_=28PR_Lublin=29?=<jak.kowalski@testdomain.com.pl>
*** Script: gs.log(TEST string): =?iso-8859-2?Q?Kwa=B6niak_<Janusz>_=28PR_Lublin=29?=<jak.kowalski@testdomain.com.pl>

Thanks
Artur

**Comment by jneale** [comment]
This is deliberate so that any comments that are generated that contain things like HTML links will render for easier debugging. You can use the HTML Message Format option in the settings to display only as text.

<img width="333" alt="image" src="https://github.com/jneale/Xplore/assets/1355440/bff93c21-72e5-4dbe-9424-f56d08a36c47">
