### ISSUE TITLE
Integrate Dark Mode

### ISSUE THREAD

**Issue by dk5ax** [jneale/Xplore#79]
Is it possible to include either the SN theme or at least allow switching to a dark background?

**Comment by jneale** [comment]
It's a standalone single page app so cannot use the native themes, however you can choose from a bunch of Sublime themes in the settings. Click the cog icon on the left and it's the first setting at the top.

<img width="401" alt="image" src="https://github.com/jneale/Xplore/assets/1355440/bc6c3fc3-a413-4d64-9bdc-8e8e19ef9adb">
