### ISSUE TITLE
Enhancement request: ui context button

### ISSUE THREAD

**Issue by jimfricker** [jneale/Xplore#82]
Hi,
Love this tool. Very useful. 

I have a very minor enhancement request. 

In ui script snd_xplore_shortcuts.openQuery, can the line 
```javascript
var log = [];
```
Be moved to the very top of the run function? This way extra info can be added to the output before the query is performed.

As I said very minor change and IMHO it makes it easier to use the log variable at different stages of the function. I find myself manually moving it every time I use it.
cheers James

**Comment by jneale** [comment]
Thanks! Should be fine.

**Comment by jneale** [comment]
Moved the log definition to the top of the run function.
