### ISSUE TITLE
Scoped script execution is not working in Xanadu release

### ISSUE THREAD

**Issue by ZOACMACK** [jneale/Xplore#88]
After uprading an instance to Xanadu release, the execution of scripts within an application scope (not global) is not working anymore.

When executing any script, the "Output" will always be null.
![image](https://github.com/user-attachments/assets/d795ecb8-447a-420f-9884-36d99ba1d4c0)

This is probably caused by a change in the security logic of GlideScopedEvaluator, but for which I couldn't find an official note in the Xanadu release notes - still, the logic behind definitely changed.

As it seems, the instance will now not allow to dynamically override the associated scope (sys_scope) of a GlideRecord anymore before the GlideRecord is passed to GlideScopedEvaluator.evaluateScript(). This technique is currently used to execute scripts in another scope by Xplore within /src/Processors/snd_xplore.js at line 572-585. Thus, this is now not working anymore.

**Comment by jneale** [comment]
Thanks for raising the issue. I have seen this and have a fix coming out shortly.

**Comment by dhubbard-ag** [comment]
Hi, any update on this?

**Comment by Dor7123** [comment]
+1, love xplore, shame it's broken now for scoped apps on xandau

**Comment by Naveen0921** [comment]
Hello,
Any upgrade on this?

**Comment by jneale** [comment]
Fixed.

**Comment by dhubbard-ag** [comment]
For those that have commented (and have notifications on) I notice that 5.01 is now released [https://github.com/jneale/Xplore/tree/master/dist](https://github.com/jneale/Xplore/tree/master/dist)
