### ISSUE TITLE
Open List with Xplore does not copy the filter since version 5.0

### ISSUE THREAD

**Issue by hsabathy** [jneale/Xplore#90]
Was it a deliberate feature change in Xplore 5.0 to not copy the filter to Encoded Query when opeining a List in Xplore?

Repro on PDI:
Open List of network gear by Cisco
https://instancexyz.service-now.com/cmdb_ci_netgear_list.do?sysparm_query=manufacturer%3Db7e831bdc0a80169015ae101f3c4d6cd&sysparm_view=

Right-click on any Column header, "Open list in Xplore",  the resulting code is:
  var gr = new GlideRecord('cmdb_ci_netgear');
  //gr.orderBy('name'); 
  // ....
  gr.query();

Counter-example : how it did work with version 4.13 and how itt is more handy:
Open List with Xplore,  the resulting code contains the filter:
    var gr = new GlideRecord('cmdb_ci_netgear');
    gr.addEncodedQuery('manufacturer=b7e831bdc0a80169015ae101f3c4d6cd');
    //gr.orderBy('name');
    // ...
    gr.query();

**Comment by jneale** [comment]
Definitely not a deliberate feature change!
To fix now, please update UI Script snd_xplore_shortcuts, line 36 to be: `        encoded_query,`

**Comment by hsabathy** [comment]
Wow! Thank you, 
this works : )

**Comment by jneale** [comment]
Fixed in 5.01 now on Share.
